const IP_ADDRESS_PART = "http://10.20.102.";
const NEWS_SERVER_PORT = "5001";
const POSTGRES_SERVER_PORT = "5002";

const IP_LAST_OCTET = "154";

const NEWS_SERVER_ADDRESS = `${IP_ADDRESS_PART}${IP_LAST_OCTET}:${NEWS_SERVER_PORT}`;
const POSTGRES_SERVER_ADDRESS = `${IP_ADDRESS_PART}${IP_LAST_OCTET}:${POSTGRES_SERVER_PORT}`;

export {
  NEWS_SERVER_ADDRESS,
  NEWS_SERVER_PORT,
  POSTGRES_SERVER_ADDRESS,
  POSTGRES_SERVER_PORT,
};
