const IP_ADDRESS_PART = "http://192.168.0.";
const NEWS_SERVER_PORT = "5001";
const POSTGRES_SERVER_PORT = "5002";

const IP_LAST_OCTET = "15";

const NEWS_SERVER_ADDRESS = `${IP_ADDRESS_PART}${IP_LAST_OCTET}:${NEWS_SERVER_PORT}`;
const POSTGRES_SERVER_ADDRESS = `${IP_ADDRESS_PART}${IP_LAST_OCTET}:${POSTGRES_SERVER_PORT}`;

console.log(POSTGRES_SERVER_ADDRESS);

export {
  NEWS_SERVER_ADDRESS,
  NEWS_SERVER_PORT,
  POSTGRES_SERVER_ADDRESS,
  POSTGRES_SERVER_PORT,
};
