const IP_LAST_OCTET = "221";
const IP_ADDRESS_PART = "http://10.20.102.";
const SERVER_PORT = "5001";

const SERVER_ADDRESS = `${IP_ADDRESS_PART}${IP_LAST_OCTET}:${SERVER_PORT}`;

export { SERVER_ADDRESS, SERVER_PORT };
