const ActionTypes = {
  TOGGLE_MENU: "TOGGLE_MENU",
  SET_PLAYER_SELECTED: "SET_PLAYER_SELECTED",
  SET_SELECTED_SEASON: "SET_SELECTED_SEASON",
  SET_OVERVIEW: "SET_OVERVIEW",
  SET_SELECTED_CATEGORY: "SET_SELECTED_CATEGORY",
};

export default ActionTypes;
