import { IMAGES } from "./constants";

const teamLogos = {
  "Newcastle United": IMAGES.ARSENAL,
  "Tottenham Hotspur": IMAGES.MUN,
};

const actualData = [
  {
    datetime: "2017-06-13 12:30:00",
    team1_name: "Newcastle United",
    team1_goals: 0,
    team2_name: "Tottenham Hotspur",
    team2_goals: 2,
  },
  {
    datetime: "2017-07-13 12:30:00",
    team1_name: "Newcastle United",
    team1_goals: 0,
    team2_name: "Tottenham Hotspur",
    team2_goals: 2,
  },
  {
    datetime: "2017-08-13 12:30:00",
    team1_name: "Newcastle United",
    team1_goals: 0,
    team2_name: "Tottenham Hotspur",
    team2_goals: 2,
  },
  {
    datetime: "2017-09-13 12:30:00",
    team1_name: "Newcastle United",
    team1_goals: 0,
    team2_name: "Tottenham Hotspur",
    team2_goals: 2,
  },
  {
    datetime: "2017-10-13 12:30:00",
    team1_name: "Newcastle United",
    team1_goals: 0,
    team2_name: "Tottenham Hotspur",
    team2_goals: 2,
  },
];

const matches = actualData.map((match) => ({
  home: match.team1_name,
  homeScore: match.team1_goals,
  homeLogo: teamLogos[match.team1_name], // 팀 이름에 해당하는 로고를 매핑합니다
  away: match.team2_name,
  awayScore: match.team2_goals,
  awayLogo: teamLogos[match.team2_name], // 팀 이름에 해당하는 로고를 매핑합니다
  datetime: match.datetime, // 경기 날짜와 시간
}));

const timelineEvents = [
  { time: "10", type: "goal", team: "home", player: "Player 1" },
  { time: "27", type: "yellow-card", team: "away", player: "Player 2" },
  { time: "45+2", type: "goal", team: "away", player: "Player 3" },
  { time: "59", type: "red-card", team: "home", player: "Player 4" },
  { time: "75", type: "goal", team: "home", player: "Player 5" },
];

const matchDetails = [
  { label: "점유율", homeData: "40%", awayData: "60%" },
  { label: "기대 득점", homeData: "1.2", awayData: "2.8" },
  { label: "슈팅", homeData: "10", awayData: "10" },
  { label: "유효 슈팅", homeData: "4", awayData: "3" },
];

const teams = [
  {
    rank: 1,
    logo: "https://i.namu.wiki/i/jAvcfbetxbl2lvkrJkQQRwiw52fiwNd3AGv__6XDZXBXX3Q5sjvUN2T7LkGxTI1pUVexTqWNpiGRiBBfO0vtPsc2hmiQhqZear3lPeqf0lyH7fWci4qxvwR0Zo5g2jlh8D-MetOL_ymO9yuRQsOWig.svg",
    name: "Liverpool",
    games: 38,
    points: 99,
    wins: 32,
    draws: 3,
    losses: 3,
    goalsFor: 85,
    goalsAgainst: 33,
    goalDifference: 52,
  },
  {
    rank: 2,
    logo: "https://i.namu.wiki/i/upN2Kwf8mJWzSLu6agfVxjNs6d6Bxt7nXONnTBBdfRlHL9t66w0NgEySKcIIrMxyT5_TE6472pUDwzeKaR2rDpvUyl7S-U9YVqGz_WC7q3yvgAomU-G33E19bCduHoghrDmJnfSzsaEUJBV4WfaEZg.svg",
    name: "Manchester City",
    games: 38,
    points: 81,
    wins: 26,
    draws: 3,
    losses: 9,
    goalsFor: 102,
    goalsAgainst: 35,
    goalDifference: 67,
  },
  {
    rank: 3,
    logo: "https://i.namu.wiki/i/J0r7UFY-fO7y7U__uu5OIdYb_i4RPcxXb5rjiicLkRiZPYaI8IE5fifoycpo49CAmEW2NLFledAL5O0duO48uRnx2J26NMV3SwahYm7FV9nisaZq_Fmvpf5adowa30DzkMxZe9_cIFd-aQAY-hNKRQ.svg",
    name: "Manchester United",
    games: 38,
    points: 66,
    wins: 18,
    draws: 12,
    losses: 8,
    goalsFor: 66,
    goalsAgainst: 36,
    goalDifference: 30,
  },
  {
    rank: 4,
    logo: "https://i.namu.wiki/i/a8hb2HwSdhNodharwUeVYcLXxH913qLSQ55W17hDAxl9DbJnk3xovl_vdWaxFx_ZOC7-tpcKe7iM50UwbkOWnAVIKvwU3ldocRj-_P9zEKlbEpwYIMSxhzYkYkj6BANI5YYNpqWQvIQcVlV0DhNfXw.svg",
    name: "Chelsea",
    games: 38,
    points: 66,
    wins: 20,
    draws: 6,
    losses: 12,
    goalsFor: 69,
    goalsAgainst: 54,
    goalDifference: 15,
  },
  {
    rank: 5,
    logo: "https://i.namu.wiki/i/fDcCG58t2yBuvZtV69DsSQf-5YKnni9r6juGFR5eRE8Gk1fXH9Soyv9BKLi9kBtHEg8vbvYv-32h-vsEKKt_mAhCcuEeF7VacYUpImAF5t7XayV2r374iJcmDwALshqZ2eEdu9qz5lSosma7ZaS84g.svg",
    name: "Leicester City",
    games: 38,
    points: 62,
    wins: 18,
    draws: 8,
    losses: 12,
    goalsFor: 67,
    goalsAgainst: 41,
    goalDifference: 26,
  },
  {
    rank: 6,
    logo: "https://i.namu.wiki/i/SrmRFXS7XtTsSZKVvQySltT_3CSukuwE3wwNEqrETJwUVobQABrYZIN5f_ym_oJCSgr7Lb5M7ErSlAtWb89LNA.svg",
    name: "Tottenham Hotspur",
    games: 38,
    points: 59,
    wins: 16,
    draws: 11,
    losses: 11,
    goalsFor: 61,
    goalsAgainst: 47,
    goalDifference: 14,
  },
  {
    rank: 7,
    logo: "https://i.namu.wiki/i/8eg4BRvpFDFHJpcx-RM9OClNqkdCJNmt46Bht7N_DwOCmEj0RfphZz54xG3WC6mNSd5mpsSC_Ure5GRz7oXlr53w9qN5vvUeHBGRT7yfvvsrNU0M7r48Eyc5hK69tlDdOPz_n5qYnu4du2cq0C3HHA.svg",
    name: "Wolverhampton Wanderers",
    games: 38,
    points: 59,
    wins: 15,
    draws: 14,
    losses: 9,
    goalsFor: 51,
    goalsAgainst: 40,
    goalDifference: 11,
  },
  {
    rank: 8,
    logo: "https://i.namu.wiki/i/ixBWXAdL9fuPHJPfntKA5K58r77boMlsKoVyS4M04Agz57TL8VDkqu_8TR_o69i-Kcn5Jb1_8lbuYVjDdeJdjjk-rS9UY5ImoUCsg2Ar7NMX1VxburMnObbV6AVhpfy0NdGYxE6JA-hKKAp-MxFAQA.svg",
    name: "Arsenal",
    games: 38,
    points: 56,
    wins: 14,
    draws: 14,
    losses: 10,
    goalsFor: 56,
    goalsAgainst: 48,
    goalDifference: 8,
  },
  {
    rank: 9,
    logo: "https://i.namu.wiki/i/uiJz5Q5wffr4C7rMZTyuvjYHYD6IQT1ZlR2NH6wnyngKqTKVPnzj9jGUZyqEL3fo63MIi9qgfgtQ8Oy9G7CRKoDakIBbP5dENZ5YzCUX7maOzl5L9sv5UaHitcGgo4pHP5_T9v-oMVrDtxn1m3CtIQ.svg",
    name: "Sheffield United",
    games: 38,
    points: 54,
    wins: 14,
    draws: 12,
    losses: 12,
    goalsFor: 39,
    goalsAgainst: 39,
    goalDifference: 0,
  },
  {
    rank: 10,
    logo: "https://i.namu.wiki/i/faFXTUCJl_lBu9WVpXY9cV959Lg0LhsXMI_YEcdHDmGUUpRPC77n8ecJpzDBgotmSwkH00MTKOLBtfALIaVor_ZsuHtjDt6ZtEgC9kGCWxOhll3Jnk4XVKunDSi0XQuuZAKGpxNcl9MPLb98QmnSZg.svg",
    name: "Burnley",
    games: 38,
    points: 54,
    wins: 15,
    draws: 9,
    losses: 14,
    goalsFor: 43,
    goalsAgainst: 50,
    goalDifference: -7,
  },
  {
    rank: 11,
    logo: "https://i.namu.wiki/i/NxHEhbIwr1fNK5lLH-CNtZ6-I-8hSF5PWaw9AN4vw8PzgBBQSHSC6PIEKM2Xb2Md1rxvbSQ6mffMaz5WGlKhuvKknYVbbmEUW4MdUd8VF2J8x66UZg2-gG8gn88dd2biolV1xNhKTVASQhiqoXte1Q.svg",
    name: "Southampton",
    games: 38,
    points: 52,
    wins: 15,
    draws: 7,
    losses: 16,
    goalsFor: 51,
    goalsAgainst: 60,
    goalDifference: -9,
  },
  {
    rank: 12,
    logo: "https://i.namu.wiki/i/GHNqtoizh9lCM2HK8wRsGl7ab1WUIHwFBzhunCyPA1d1-eA9mvzSOMsK4hoVUZuSPttwZxOntft_tAbr88soLZOFBd8uYj05T0QvTtn54SBzZmhdHxuZRmSvrCY4FqVHuF9E9SEY7y43Ng2BGCL4cw.svg",
    name: "Everton",
    games: 38,
    points: 49,
    wins: 13,
    draws: 10,
    losses: 15,
    goalsFor: 44,
    goalsAgainst: 56,
    goalDifference: -12,
  },
  {
    rank: 13,
    logo: "https://i.namu.wiki/i/g5cI7_nvavwSDUkCwHvG-nY-IZX7KEMDB9Iy_cVh80zKJI5H0cOZjaYNidoleYC5NZ6BDh7NZvdmqoHIO7YV5ml5d78AFbjMGD6lgdKE8BNWpprj3vS3dHs7CRG1BKNYeUe-c9FVM2fn7PGp-M0e_Q.svg",
    name: "Newcastle United",
    games: 38,
    points: 44,
    wins: 11,
    draws: 11,
    losses: 16,
    goalsFor: 38,
    goalsAgainst: 58,
    goalDifference: -20,
  },
  {
    rank: 14,
    logo: "https://i.namu.wiki/i/43AlkMDowSKGDt8n4MhCbtUCyB4hPE-4DMtgGQw4Smd3rAhhh4NNOdaSm_mqDabZCSY4ULtIIj69M0NrJhxgScCqY6701OBg_i6bSPSg_a_rtxtyO9P5M9QpU9Q4GRCpZnPlpZeq8Sff_9JSE35YqA.svg",
    name: "Crystal Palace",
    games: 38,
    points: 43,
    wins: 11,
    draws: 10,
    losses: 17,
    goalsFor: 31,
    goalsAgainst: 50,
    goalDifference: -19,
  },
  {
    rank: 15,
    logo: "https://i.namu.wiki/i/D7_zyWfZlBCxB79VR4vvmTBywkO460zR7lvR7BZoxUc8OrRYLuk2zPZ8oE2Ux55ObEy4PgIGUWP7ktp9uErF_g.svg",
    name: "Brighton & Hove Albion",
    games: 38,
    points: 41,
    wins: 9,
    draws: 14,
    losses: 15,
    goalsFor: 39,
    goalsAgainst: 54,
    goalDifference: -15,
  },
  {
    rank: 16,
    logo: "https://i.namu.wiki/i/irUsgCYtSIM8oC-EU9kGOi9gT6UcdqC2sTn2GxHt0AXGhN1RH2psqVzWJklSTx7SGl9ii0Pr53Vxn2qh0-AZAQ.svg",
    name: "West Ham United",
    games: 38,
    points: 39,
    wins: 10,
    draws: 9,
    losses: 19,
    goalsFor: 49,
    goalsAgainst: 62,
    goalDifference: -13,
  },
  {
    rank: 17,
    logo: "https://i.namu.wiki/i/A_OPCscwAa6uRdxqeHzHTPL-vTMucXhGRUOPXQd8dTfwEeKpySKP4UoBOkxPRTeUV22AAxWqVB2l7rz_2vVnAYyh77rAVelA0m9yGVVC7dPky5BiMBMn-dsVrOt18Rn0bYze6oj4xnHGaQNpuP64tg.svg",
    name: "Aston Villa",
    games: 38,
    points: 35,
    wins: 9,
    draws: 8,
    losses: 21,
    goalsFor: 41,
    goalsAgainst: 67,
    goalDifference: -26,
  },
  {
    rank: 18,
    logo: "https://i.namu.wiki/i/uvGTJJSSgzeq2cA_Jmnb5RGw6xkJXMbVInjrygkZzqVwI9MgyHFwFwy6vY_y70QGjTjDR_4nXYiyHtkplQLt9g.svg",
    name: "AFC Bournemouth",
    games: 38,
    points: 34,
    wins: 9,
    draws: 7,
    losses: 22,
    goalsFor: 40,
    goalsAgainst: 65,
    goalDifference: -25,
  },
  {
    rank: 19,
    logo: "https://i.namu.wiki/i/ifH5wOL0idzQMokEVHj1Vu_3s_7pa2t6PaoaMf41riXgb58vOv7mshS9Q1_nknX0kESv-tDXvpgYVf5BVDlN_-nO7PdgG9cZiHdDsLT-61rdYNnXR73CR3l9geLvooeg4jgjxRxDuRMMnxoiKbM77Q.svg",
    name: "Watford",
    games: 38,
    points: 34,
    wins: 8,
    draws: 10,
    losses: 20,
    goalsFor: 36,
    goalsAgainst: 64,
    goalDifference: -28,
  },
  {
    rank: 20,
    logo: "https://i.namu.wiki/i/fC1Yv-kQtJwrqxallBQ8dl3JgEQgNJ5Smsc90wUU6Lgk5ynxeDdfRSsAocIQ4-4dAxUhedFEwEE9JZADYE7Kyli8y89KnYm7xfQCU9Dy_bp5EMNdn9TBDoLBd8vtZaqErw6InWLlqyR3qCXyraPYiw.svg",
    name: "Norwich City",
    games: 38,
    points: 21,
    wins: 5,
    draws: 6,
    losses: 27,
    goalsFor: 26,
    goalsAgainst: 75,
    goalDifference: -49,
  },
];

export { matches, timelineEvents, matchDetails, teams };
