export const ActionTypes = {
  SET_NEWS: "SET_NEWS",
  SET_SELECTED_URL: "SET_SELECTED_URL",
  SET_LOADING: "SET_LOADING",
  SET_REFRESHING: "SET_REFRESHING",
  SET_IMAGE_HEIGHT: "SET_IMAGE_HEIGHT",
};
